---
title: '241 Project (Summer 2017): Effect of Meditation on Blood Pressure'
author: "Erika Lawrence, Thong Bui, Matt Post"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(data.table)
library(sandwich)
library(lmtest)
```

# Exploring data

```{r}
d <- fread("../data/meditation.csv")
# Should be 30 subjects
nrow(d)
str(d)
d <- data.table(d)
# Reverse group number: 1 is meditation first (treatment), 0 is coloring 1st
d2 <- d[ , .(Group = ifelse(Group == 0, 1, 0), 
             is_online = ifelse(Online_in_person == 'O', 1, 0),
             B4_Med_BP_Sys,
             After_Med_BP_Sys,
             B4_color_BP_Sys,
             After_color_BP_Sys) ]
summary(d2)

#hist(d2$Group)
#hist(d2$is_online, breaks=30)
par(mfrow=c(2,2))
hist(d2$B4_Med_BP_Sys, breaks = 30)
hist(d2$After_Med_BP_Sys, breaks = 30)
hist(d2$B4_color_BP_Sys, breaks = 30)
hist(d2$After_color_BP_Sys, breaks = 30)

library(RColorBrewer)
#display.brewer.all()
cols<-brewer.pal(n=3,name="Set1")
# Note: Group 0 is treatment group!
cols_t1<-cols[d2$Group+1]
med_diff <- d2$B4_Med_BP_Sys - d2$After_Med_BP_Sys
color_diff <-  d2$B4_color_BP_Sys - d2$After_color_BP_Sys
par(mfrow =c(1,2))
plot(d2$Group ~ med_diff , col=cols_t1, pch=16)
legend("center",legend=c("Group 1: meditation", "Group 0: coloring"), col=cols_t1, pch=16)
plot(d2$Group ~ color_diff , col=cols_t1, pch=16)
legend("center",legend=c("Group 1: meditation", "Group 0: coloring"), col=cols_t1, pch=16)

# Plot b4 vs after meditation for 2 groups
plot(After_Med_BP_Sys ~ B4_Med_BP_Sys, data=d2 , col=cols_t1, pch=16)
legend(x=100,y=136, legend=c("Group 1: meditation", "Group 0: coloring"), col=cols_t1, pch=16, xpd=TRUE)

# Plot b4 vs after coloring for 2 groups
plot(After_color_BP_Sys ~ B4_color_BP_Sys, data=d2 , col=cols_t1, pch=16)
legend(x=100,y=143, legend=c("Group 1: meditation", "Group 0: coloring"), col=cols_t1, pch=16, xpd=TRUE)

```

# Regression model within-person

##### Coloring first (group 0): placebo
##### Meditation first (group 1): treatment

```{r}

m <- lm(After_Med_BP_Sys ~ B4_Med_BP_Sys + Group + B4_Med_BP_Sys * Group, data=d2)
coeftest(m, vcovHC(m))

m2 <- lm(After_color_BP_Sys ~ B4_color_BP_Sys + Group + B4_color_BP_Sys * Group, data=d2)
coeftest(m2, vcovHC(m2))
